### ISSUE TITLE
Unexpected hash

### ISSUE THREAD

**Issue by midn1** [emscripten-ports/SDL2#120]
Trying to build with `emcc -s WASM=0 -s USE_SDL=2 xxx -lSDL2main -lSDL2`.
```
emcc: warning: Assuming object file output in the absence of `-c`, based on output filename. Add with `-c` or `-r` to avoid this warning [-Wemcc]
system_libs:INFO: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_20.zip
Traceback (most recent call last):
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/emcc.py", line 3982, in <module>
    sys.exit(run(sys.argv))
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/emcc.py", line 2164, in run
    compile_source_file(i, input_file)
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/emcc.py", line 2141, in compile_source_file
    cmd = get_clang_command([input_file]) + ['-c', '-o', output_file]
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/emcc.py", line 2112, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/tools/system_libs.py", line 1958, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 98, in process_args
    get(ports, settings, shared)
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 18, in get
    ports.fetch_project('sdl2', 'https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip', SUBDIR, sha512hash=HASH)
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/tools/system_libs.py", line 1907, in fetch_project
    retrieve()
  File "/home/xxx/Downloads/emsdk/upstream/emscripten/tools/system_libs.py", line 1861, in retrieve
    raise RuntimeError('Unexpected hash: ' + actual_hash + '\n'
RuntimeError: Unexpected hash: 8effb53923f01c05fd323f7c55ca65546e61168bf783ecb4c01809f87e0cc6c7f2eab6edca7f28edac4d815e51285a9f5800beaf1088d30a619b6c700befcaaa
If you are updating the port, please update the hash in the port module.
```

**Comment by jcelerier** [comment]
Same issue here (emsdk 1.39.8,  Unexpected hash: 03e154a70b262153fe5a8794d1803daddeffd7126c8b90ba1e7ba867c22c7ebc1a73b11e41f4b79d82c283ad8a5d518261b6939d19a33d3474096a39da5aecb2)

**Comment by jcelerier** [comment]
Also same issue with emsdk 2.0.14

**Comment by jcelerier** [comment]
the hash is wrong because the downloaded files are an error response from the server:

```
Deprecated authentication method. Create a Personal Access Token to access: https://github.com/settings/tokens
```

**Comment by kripken** [comment]
I'm not sure how github authentication works, but I'm surprised github asks for a token there. Perhaps SSL is not supported by your system's Python, and github considers non-SSL to be deprecated?

**Comment by jcelerier** [comment]
> Perhaps SSL is not supported by your system's Python

hm, how would I go about checking that ? I'm using archlinux so everything is pretty up-to-date... maybe a python2 / python3 thing ?

**Comment by kripken** [comment]
I'm not sure, but I'd try a newer version of Python if possible, and preferably Python 3.

**Comment by jcelerier** [comment]
My /usr/bin/python is 3.9.1

**Comment by doccaico** [comment]
I have the same error. My Python version is 3.8.5

**Comment by jcelerier** [comment]
still happening :(
